services:
  db:
    image: postgres:16-alpine
    hostname: db
    ports:
      - "5332:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  kc:
    image: quay.io/keycloak/keycloak:26.4
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    restart: always
